[database]
localhost ansible_connection=local
[database:vars]
db_name=cinema
db_user=postgres
db_password=postgres
db_port=5432

[backend]
localhost ansible_connection=local
[backend:vars]
app_name=cinema-backend
app_port=8080
db_host=192.168.56.12

[frontend]
localhost ansible_connection=local
[frontend:vars]
app_port=4300
backend_host=192.168.56.11
backend_port=8080

[build]
localhost ansible_connection=local
[build:vars]
GITHUB_PAT=github_pat_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
nexus_admin_user=admin
nexus_admin_password=admin123
nexus_http_port=8081
nexus_raw_repo_name=cinema-artifacts
nexus_host=192.168.56.21

backend_host=192.168.56.11
frontend_host=192.168.56.10
frontend_port=4300
backend_port=8080
db_host=192.168.56.12
app_name=cinema-backend
app_port=8080

db_name=cinema
db_user=postgres
db_password=postgres
db_port=5432

[Artifact]
localhost ansible_connection=local
[Artifact:vars]
nexus_admin_user=admin
nexus_admin_password=admin123
nexus_http_port=8081
nexus_raw_repo_name=cinema-artifacts

[revproxy]
localhost ansible_connection=local

[revproxy:vars]
frontend_host=192.168.56.10
frontend_port=4300
backend_host=192.168.56.11
backend_port=8080
