Vagrant.configure("2") do |config|
  # Domyślne ustawienia dla wszystkich maszyn
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024 
    vb.cpus   = 1
  end

  #config.vbguest.auto_update = false

  # ============================== RevProxy ==============================
  config.vm.define "RevProxy" do |proxy|
    proxy.vm.box = "debian/bookworm64"
    proxy.vm.hostname = "revproxy"
    proxy.vm.network "private_network", ip: "192.168.56.13"
    proxy.vm.network "forwarded_port", guest: 80, host: 80

    proxy.vm.provider "virtualbox" do |vb|
      vb.memory = 512    
      vb.cpus   = 1
    end

    proxy.vm.provision "ansible_local" do |ansible|
      ansible.install        = true
      ansible.become         = true
      ansible.playbook       = "RevProxy.yml"
      ansible.inventory_path = "inventory.ini"
      ansible.limit          = "revproxy"
      ansible.verbose        = "v"
    end
  end

  # ============================== DATABASE ==============================
  config.vm.define "database" do |db|
    db.vm.box = "debian/bookworm64"
    db.vm.hostname = "database"
    db.vm.network "private_network", ip: "192.168.56.12"
    db.vm.network "forwarded_port", guest: 5432, host: 5433

    db.vm.provider "virtualbox" do |vb|
      vb.memory = 1536   
      vb.cpus   = 1
    end

    db.vm.provision "ansible_local" do |ansible|
      ansible.install        = true
      ansible.become         = true
      ansible.playbook       = "database.yml"
      ansible.inventory_path = "inventory.ini"
      ansible.limit          = "database"
      ansible.verbose        = "v"
    end
  end

  # =============================== BACKEND ==============================
  config.vm.define "backend" do |backend|
    backend.vm.box = "generic/ubuntu2204"
    backend.vm.hostname = "backend"
    backend.vm.network "private_network", ip: "192.168.56.11"
    backend.vm.network "forwarded_port", guest: 8080, host: 8080
    backend.vm.synced_folder ".", "/vagrant"
    backend.vm.synced_folder "../../application/backend", "/app",
                             mount_options: ["dmode=775,fmode=664"]

    backend.vm.provider "virtualbox" do |vb|
      vb.memory = 1536   
      vb.cpus   = 1
    end

    backend.vm.provision "ansible_local" do |ans|
      ans.install        = true
      ans.playbook       = "backend.yml"
      ans.inventory_path = "inventory.ini"
    end
  end

  # ============================== FRONTEND ==============================
  config.vm.define "frontend" do |frontend|
    frontend.vm.box = "generic/ubuntu2204"
    frontend.vm.hostname = "frontend"
    frontend.vm.network "private_network", ip: "192.168.56.10"
    frontend.vm.network "forwarded_port", guest: 4300, host: 4300
    frontend.vm.synced_folder ".", "/vagrant"
    frontend.vm.synced_folder "../../application/frontend", "/app",
                               mount_options: ["uid=1000","gid=1000",
                                               "dmode=775","fmode=775"]

    frontend.vm.provider "virtualbox" do |vb|
      vb.memory = 1024   
      vb.cpus   = 1
    end

    frontend.vm.provision "ansible_local" do |ansible|
      ansible.install        = true
      ansible.playbook       = "frontend.yml"
      ansible.inventory_path = "inventory.ini"
      ansible.limit          = "frontend"
    end
  end

  # ============================== BUILD MACHINE ==============================
  config.vm.define "build" do |build|
    build.vm.box = "generic/ubuntu2204"
    build.vm.hostname = "buildMachine"
    build.vm.network "private_network", ip: "192.168.56.20"
    build.vm.synced_folder ".", "/vagrant"
    build.vm.synced_folder "build/shared", "/app",
                                   mount_options: ["uid=1000","gid=1000",
                                                   "dmode=775","fmode=775"]

    build.vm.provider "virtualbox" do |vb|
      vb.memory = 2048 
      vb.cpus   = 1
    end

    build.vm.provision "ansible_local" do |ansible|
      ansible.playbook       = "build/build.yml"
      ansible.inventory_path = "inventory.ini"
      ansible.limit          = "build"
      ansible.verbose        = "v"
    end
  end

  # ============================== REPOSITORY MACHINE ==============================
  config.vm.define "Artifact" do |artifact|
    artifact.vm.box = "debian/bookworm64"
    artifact.vm.hostname = "repositoryMachine"
    artifact.vm.network "private_network", ip: "192.168.56.21"
    artifact.vm.synced_folder ".", "/vagrant"

    artifact.vm.provider "virtualbox" do |vb|
      vb.memory = 4096   
      vb.cpus   = 1
    end

    artifact.vm.provision "ansible_local" do |ansible|
      ansible.playbook       = "Artifact.yml"
      ansible.inventory_path = "inventory.ini"
      ansible.limit          = "Artifact"
      ansible.verbose        = "v"
    end
  end
end
