Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus   = 2
  end
#config.vbguest.auto_update = false
  # ============================== DATABASE ==============================
  config.vm.define "database" do |db|
    db.vm.box = "debian/bookworm64"
    db.vm.hostname = "database"
    db.vm.network "private_network", ip: "192.168.56.12"
    db.vm.network "forwarded_port", guest: 5432, host: 5433
    db.vm.provision "ansible_local" do |ansible|
      ansible.install = true
      ansible.become  = true
      ansible.playbook = "ansible/database.yml"
      ansible.inventory_path = "ansible/inventory.ini"
      ansible.limit = "database"       
      ansible.verbose = "v"
    end
  end

  # =============================== BACKEND ==============================
  config.vm.define "backend" do |backend|
    backend.vm.box = "debian/bookworm64"
    backend.vm.hostname = "backend"
    backend.vm.network "private_network", ip: "192.168.56.11"
    backend.vm.network "forwarded_port", guest: 8080, host: 8080
    backend.vm.synced_folder "../application/backend", "/app", mount_options: ["dmode=775,fmode=664"]
    backend.vm.provision "ansible_local" do |ans|
      ans.install = true
      ans.playbook = "ansible/backend.yml"
      ans.inventory_path = "ansible/inventory.ini"
  end
end

  # ============================== FRONTEND ==============================
  config.vm.define "frontend" do |frontend|
    frontend.vm.box = "debian/bookworm64"
    frontend.vm.hostname = "frontend"
    frontend.vm.network "private_network", ip: "192.168.56.10"
    frontend.vm.network "forwarded_port", guest: 4300, host: 4300
    frontend.vm.synced_folder "../application/frontend", "/app", mount_options: ["uid=1000","gid=1000","dmode=775","fmode=775"]
    frontend.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "ansible/frontend.yml"
      ansible.inventory_path = "ansible/inventory.ini"
      ansible.limit = "frontend"
      ansible.verbose = "v"
    end
  end
end