[database]
localhost ansible_connection=local
[database:vars]
db_name=cinema
db_user=postgres
db_password=postgres
db_port=5432

[backend]
localhost ansible_connection=local
[backend:vars]
app_name=cinema-backend
app_port=8080
db_host=192.168.56.12

[frontend]
localhost ansible_connection=local
[frontend:vars]
app_port=4300
backend_host=192.168.56.11
backend_port=8080